# MAT281 - Laboratorio N°02



<a id='p1'></a>

## Problema 01

Una **media móvil simple** (SMA) es el promedio de los últimos $k$ datos anteriores, es decir, sea $a_1$,$a_2$,...,$a_n$ un arreglo $n$-dimensional, entonces la SMA se define por:

$$\displaystyle sma(k) =\dfrac{1}{k}(a_{n}+a_{n-1}+...+a_{n-(k-1)}) = \dfrac{1}{k}\sum_{i=0}^{k-1}a_{n-i}  $$ 


Por otro lado podemos definir el SMA con una venta móvil de $n$ si el resultado nos retorna la el promedio ponderado avanzando de la siguiente forma:

* $a = [1,2,3,4,5]$, la SMA con una ventana de $n=2$ sería:
 * sma(2) = [promedio(1,2), promedio(2,3), promedio(3,4), promedio(4,5)] = [1.5, 2.5, 3.5, 4.5]


* $a = [1,2,3,4,5]$, la SMA con una ventana de $n=3$ sería:
 * sma(3) = [promedio(1,2,3), promedio(2,3,4), promedio(3,4,5)] = [2.,3.,4.]


Implemente una función llamada `sma` cuyo input sea un arreglo unidimensional $a$ y un entero $n$, y cuyo ouput retorne el valor de la media móvil simple sobre el arreglo de la siguiente forma:

* **Ejemplo**: *sma([5,3,8,10,2,1,5,1,0,2], 2)* = $[4. , 5.5, 9. , 6. , 1.5, 3. , 3. , 0.5, 1. ]$

En este caso, se esta calculando el SMA para un arreglo con una ventana de $n=2$.

**Hint**: utilice la función `numpy.cumsum`

In [5]:
# importar librerias
import numpy as np 

### Definir Función

In [6]:
def sma(x, window_len):
    return np.convolve(x, np.ones(window_len), 'valid') / window_len

### Verificar ejemplos

In [7]:
# ejemplo 01
a = np.array([1,2,3,4,5])

np.testing.assert_array_equal(
    sma(a, window_len=2),
    np.array([1.5, 2.5, 3.5, 4.5])
)

In [8]:
# ejemplo 02
a = np.array([5,3,8,10,2,1,5,1,0,2])

np.testing.assert_array_equal(
    sma(a, window_len=2),
    np.array([4. , 5.5, 9. , 6. , 1.5, 3. , 3. , 0.5, 1. ])
)

<a id='p2'></a>

## Problema 02

La función **strides($a,n,p$)**, corresponde a transformar un arreglo unidimensional $a$ en una matriz de $n$ columnas, en el cual las filas se van construyendo desfasando la posición del arreglo en $p$ pasos hacia adelante.

* Para el arreglo unidimensional $a$ = [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], la función strides($a,4,2$), corresponde a crear una matriz de $4$ columnas, cuyos desfaces hacia adelante se hacen de dos en dos. 

El resultado tendría que ser algo así:$$\begin{pmatrix}
 1& 2 &3 &4 \\ 
 3&  4&5&6 \\ 
 5& 6 &7 &8 \\ 
 7& 8 &9 &10 \\ 
\end{pmatrix}$$


Implemente una función llamada `strides(a,n,p)` cuyo input sea:
* $a$: un arreglo unidimensional, 
* $n$: el número de columnas,
* $p$: el número de pasos hacia adelante  

y retorne la matriz de $n$ columnas, cuyos desfaces hacia adelante se hacen de $p$ en $p$ pasos. 

* **Ejemplo**: *strides($a$,4,2)* =$\begin{pmatrix}
 1& 2 &3 &4 \\ 
 3&  4&5&6 \\ 
 5& 6 &7 &8 \\ 
 7& 8 &9 &10 \\ 
\end{pmatrix}$


### Definir Función

In [9]:
def strides(a,n,p):
    M = np.zeros((n, n))
    cont = 0
    while cont < (a.shape[0]-2):
        for i in range(n):
            for j in range(n):
                M[i,j] = a[cont]
                cont = cont+1
            cont = cont-p
    return M

In [10]:
a = np.array([ 1,  2,  3])
n=2
p=1
print(strides(a,n,p))

[[1. 2.]
 [2. 3.]]


In [11]:
a = np.array([ 1,  2,  3, 4])
n=2
p=0
print(strides(a,n,p))

[[1. 2.]
 [3. 4.]]


In [12]:
a = np.array([ 1,  2,  3,  4,  5,  6,  7])
n=3
p=1
print(strides(a,n,p))

[[1. 2. 3.]
 [3. 4. 5.]
 [5. 6. 7.]]


In [13]:
a = np.array([ 1,  2,  3,  4,  5,  6,  7, 8, 9])
n=3
p=0
print(strides(a,n,p))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [14]:
a = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
n=4
p=2
print(strides(a,n,p))

[[ 1.  2.  3.  4.]
 [ 3.  4.  5.  6.]
 [ 5.  6.  7.  8.]
 [ 7.  8.  9. 10.]]


In [15]:
a = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
n=4
p=1
print(strides(a,n,p))

[[ 1.  2.  3.  4.]
 [ 4.  5.  6.  7.]
 [ 7.  8.  9. 10.]
 [10. 11. 12. 13.]]


### Verificar ejemplos

In [16]:
# ejemplo 01
a = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
n=4
p=2

np.testing.assert_array_equal(
    strides(a,n,p),
    np.array([
       [ 1,  2,  3,  4],
       [ 3,  4,  5,  6],
       [ 5,  6,  7,  8],
       [ 7,  8,  9, 10]
    ])
)

<a id='p3'></a>

## Problema 03


Un **cuadrado mágico** es una matriz de tamaño $n \times n$ de números enteros positivos tal que 
la suma de los números por columnas, filas y diagonales principales sea la misma. Usualmente, los números empleados para rellenar las casillas son consecutivos, de 1 a $n^2$, siendo $n$ el número de columnas y filas del cuadrado mágico.

Si los números son consecutivos de 1 a $n^2$, la suma de los números por columnas, filas y diagonales principales 
es igual a : $$\displaystyle M_{n} = \dfrac{n(n^2+1)}{2}$$
Por ejemplo, 

* $A= \begin{pmatrix}
 4& 9 &2 \\ 
 3&  5&7 \\ 
 8& 1 &6 
\end{pmatrix}$,
es un cuadrado mágico.

* $B= \begin{pmatrix}
 4& 2 &9 \\ 
 3&  5&7 \\ 
 8& 1 &6 
\end{pmatrix}$, no es un cuadrado mágico.

Implemente una función llamada `es_cudrado_magico` cuyo input sea una matriz cuadrada de tamaño $n$ con números consecutivos de $1$ a $n^2$ y cuyo ouput retorne *True* si es un cuadrado mágico o 'False', en caso contrario

* **Ejemplo**: *es_cudrado_magico($A$)* = True, *es_cudrado_magico($B$)* = False

**Hint**: Cree una función que valide la mariz es cuadrada y  que sus números son consecutivos del 1 a $n^2$.

### Definir Función

In [17]:
def contar(lista):
    return {i:lista.count(i) for i in lista} # Retorna cantidad de elementos repetidos en una lista

In [18]:
def es_cudrado_magico (matriz) :
    if matriz.shape[0] == matriz.shape[1]:
    
        N = len(matriz[0])   # tamaño de la matriz 
        sumas = []   # Aquí se irán guardando las sumas. Al final de verifican que sean iguales.

        # suma filas
        for i in range (N) :
            suma = 0
            for j in range (N) :
                suma += matriz[i][j]
            sumas.append (suma)

        # suma columnas
        for j in range (N) :
            suma = 0
            for i in range (N) :
                suma += matriz[i][j]
            sumas.append (suma)

        # suma diagonal (Extremo superior izquierdo -> Extremo inferior derecho)
        suma = 0
        for k in range (N):
            suma += matriz[k][k]
        sumas.append (suma)

        # suma diagonal (Extremo inferior izquierdo -> Extremo superior derecho)
        suma = 0
        for j in range (N):
            i = N - 1 - j
            suma += matriz[i][j]
        sumas.append (suma)

        # verificar que las sumas sean iguales y retornar
        numero_repetidos=contar(sumas) 
        maximo=max(numero_repetidos, key=numero_repetidos.get)
        if numero_repetidos[maximo] == len(sumas):
            return True
        else:
            return False
    else:
        print('La matriz no es cuadrada')

### Verificar ejemplos

In [19]:
# ejemplo 01
A = np.array([[4,9,2],[3,5,7],[8,1,6]])
assert es_cudrado_magico(A) == True, "ejemplo 01 incorrecto"

In [20]:
# ejemplo 02
B = np.array([[4,2,9],[3,5,7],[8,1,6]])
assert es_cudrado_magico(B) == False, "ejemplo 02 incorrecto"

In [21]:
# ejemplo 03
C = np.array([[4,2,9],[3,5,7],[8,1,6],[1,3,7]])
es_cudrado_magico(C)

La matriz no es cuadrada
